#
# normal.HMM.mllk(normal.HMM.N2W(mu.Test, sigma.Test, Gamma.Test, type="HMM"),
#                 logR,
#                 type="HMM",
#                 distribution="Normal",
#                 nu=4)



# (Gamma <- Gamma.Build.HHMM(prob.i=test$HMM.Train$Gamma,
#                           type="HHMM"))


# HMM.Stack.Plot(test$smooth.Prob,
#                test$dates)
#
# HMM.Stack.Plot(test$filtered.Prob,
#                test$dates)


# test <- HMM.Train(index <- index,
#                   Data,
#                   start.date <- start.date,
#                   end.date   <- end.date,
#                   frequency=frequency,
#                   mult=mult,
#                   # mu0=mu.Test,
#                   # sigma0=sigma.Test,
#                   Gamma0=Gamma.HMM.Diebold.w.filter,
#                   type="HMM",
#                   distribution='Normal',
#                   Transition.Type="Diebold.w.filter",
#                   PlotName = NULL,
#                   data.Origin=data.Origin,
#                   auto.assign=T,
#                   path=path,
#                   nbTicks=nbTicks,
#                   initial.Distribution = c(1,0))
#
#
# test <- HMM.Train(index <- index,
#                   Data,
#                   start.date <- start.date,
#                   end.date   <- end.date,
#                   frequency=frequency,
#                   mult=mult,
#                   # mu0=mu.Test,
#                   # sigma0=sigma.Test,
#                   Gamma0=Gamma.HMM.Diebold.w.filter,
#                   type="HMM",
#                   distribution='Student',
#                   Transition.Type="Diebold.w.filter",
#                   PlotName = NULL,
#                   data.Origin=data.Origin,
#                   auto.assign=T,
#                   path=path,
#                   nbTicks=nbTicks,
#                   initial.Distribution = c(1,0))
#
#
# test <- HMM.Train(index <- index,
#                   Data,
#                   start.date <- start.date,
#                   end.date   <- end.date,
#                   frequency=frequency,
#                   mult=mult,
#                   # mu0=mu.Test,
#                   # sigma0=sigma.Test,
#                   Gamma0=Gamma.HMM.Diebold.w.filter,
#                   type="HMM",
#                   distribution='Normal',
#                   Transition.Type="Diebold.w.filter",
#                   PlotName = NULL,
#                   data.Origin=data.Origin,
#                   auto.assign=T,
#                   path=path,
#                   nbTicks=nbTicks,
#                   initial.Distribution = c(0,1))
#
#
# test <- HMM.Train(index <- index,
#                   Data,
#                   start.date <- start.date,
#                   end.date   <- end.date,
#                   frequency=frequency,
#                   mult=mult,
#                   # mu0=mu.Test,
#                   # sigma0=sigma.Test,
#                   Gamma0=Gamma.HMM.Diebold.w.filter,
#                   type="HMM",
#                   distribution='Student',
#                   Transition.Type="Diebold.w.filter",
#                   PlotName = NULL,
#                   data.Origin=data.Origin,
#                   auto.assign=T,
#                   path=path,
#                   nbTicks=nbTicks,
#                   initial.Distribution = c(0,1))
#
#
# test <- HMM.Train(index <- index,
#                   Data,
#                   start.date <- start.date,
#                   end.date   <- end.date,
#                   frequency=frequency,
#                   mult=mult,
#                   # mu0=mu.Test,
#                   # sigma0=sigma.Test,
#                   Gamma0=Gamma.HMM.Diebold,
#                   type="HMM",
#                   distribution='Normal',
#                   Transition.Type="Diebold",
#                   PlotName = NULL,
#                   data.Origin=data.Origin,
#                   auto.assign=T,
#                   path=path,
#                   nbTicks=nbTicks,
#                   initial.Distribution = c(1,0))
#
#
# test <- HMM.Train(index <- index,
#                   Data,
#                   start.date <- start.date,
#                   end.date   <- end.date,
#                   frequency=frequency,
#                   mult=mult,
#                   # mu0=mu.Test,
#                   # sigma0=sigma.Test,
#                   Gamma0=Gamma.HMM.Diebold,
#                   type="HMM",
#                   distribution='Student',
#                   Transition.Type="Diebold",
#                   PlotName = NULL,
#                   data.Origin=data.Origin,
#                   auto.assign=T,
#                   path=path,
#                   nbTicks=nbTicks,
#                   initial.Distribution = c(1,0))
#
#
# test <- HMM.Train(index <- index,
#                   Data,
#                   start.date <- start.date,
#                   end.date   <- end.date,
#                   frequency=frequency,
#                   mult=mult,
#                   # mu0=mu.Test,
#                   # sigma0=sigma.Test,
#                   Gamma0=Gamma.HMM.Diebold,
#                   type="HMM",
#                   distribution='Normal',
#                   Transition.Type="Diebold",
#                   PlotName = NULL,
#                   data.Origin=data.Origin,
#                   auto.assign=T,
#                   path=path,
#                   nbTicks=nbTicks,
#                   initial.Distribution = c(0,1))
#
#
# test <- HMM.Train(index <- index,
#                   Data,
#                   start.date <- start.date,
#                   end.date   <- end.date,
#                   frequency=frequency,
#                   mult=mult,
#                   # mu0=mu.Test,
#                   # sigma0=sigma.Test,
#                   Gamma0=Gamma.HMM.Diebold,
#                   type="HMM",
#                   distribution='Student',
#                   Transition.Type="Diebold",
#                   PlotName = NULL,
#                   data.Origin=data.Origin,
#                   auto.assign=T,
#                   path=path,
#                   nbTicks=nbTicks,
#                   initial.Distribution = c(0,1))
#
#
# test <- HMM.Train(index <- index,
#                   Data,
#                   start.date <- start.date,
#                   end.date   <- end.date,
#                   frequency=frequency,
#                   mult=mult,
#                   # mu0=mu.Test,
#                   # sigma0=sigma.Test,
#                   Gamma0=Gamma.HMM.2,
#                   type="HMM",
#                   distribution='Normal',
#                   Transition.Type="Homogeneous",
#                   PlotName = NULL,
#                   data.Origin=data.Origin,
#                   auto.assign=T,
#                   path=path,
#                   nbTicks=nbTicks)
#
#
# test <- HMM.Train(index <- index,
#                   Data,
#                   start.date <- start.date,
#                   end.date   <- end.date,
#                   frequency=frequency,
#                   mult=mult,
#                   # mu0=mu.Test,
#                   # sigma0=sigma.Test,
#                   Gamma0=Gamma.HMM.2,
#                   type="HMM",
#                   distribution='Student',
#                   Transition.Type="Homogeneous",
#                   PlotName = NULL,
#                   data.Origin=data.Origin,
#                   auto.assign=T,
#                   path=path,
#                   nbTicks=nbTicks)
#
#
# test <- HMM.Train(index <- index,
#                   Data,
#                   start.date <- start.date,
#                   end.date   <- end.date,
#                   frequency=frequency,
#                   mult=mult,
#                   # mu0=mu.Test,
#                   # sigma0=sigma.Test,
#                   Gamma0=Gamma.HMM.3,
#                   type="HMM",
#                   distribution='Normal',
#                   Transition.Type="Homogeneous",
#                   PlotName = NULL,
#                   data.Origin=data.Origin,
#                   auto.assign=T,
#                   path=path,
#                   nbTicks=nbTicks)
#
#
# test <- HMM.Train(index <- index,
#                   Data,
#                   start.date <- start.date,
#                   end.date   <- end.date,
#                   frequency=frequency,
#                   mult=mult,
#                   # mu0=mu.Test,
#                   # sigma0=sigma.Test,
#                   Gamma0=Gamma.HMM.3,
#                   type="HMM",
#                   distribution='Student',
#                   Transition.Type="Homogeneous",
#                   PlotName = NULL,
#                   data.Origin=data.Origin,
#                   auto.assign=T,
#                   path=path,
#                   nbTicks=nbTicks)
#
#
# test <- HMM.Train(index <- index,
#                   Data,
#                   start.date <- start.date,
#                   end.date   <- end.date,
#                   frequency=frequency,
#                   mult=mult,
#                   # mu0=mu.Test,
#                   # sigma0=sigma.Test,
#                   Gamma0=Gamma.HMM.4,
#                   type="HMM",
#                   distribution='Normal',
#                   Transition.Type="Homogeneous",
#                   PlotName = NULL,
#                   data.Origin=data.Origin,
#                   auto.assign=T,
#                   path=path,
#                   nbTicks=nbTicks)
#
#
# test <- HMM.Train(index <- index,
#                   Data,
#                   start.date <- start.date,
#                   end.date   <- end.date,
#                   frequency=frequency,
#                   mult=mult,
#                   # mu0=mu.Test,
#                   # sigma0=sigma.Test,
#                   Gamma0=Gamma.HMM.4,
#                   type="HMM",
#                   distribution='Normal',
#                   Transition.Type="Homogeneous",
#                   PlotName = NULL,
#                   data.Origin=data.Origin,
#                   auto.assign=T,
#                   path=path,
#                   nbTicks=nbTicks)

# 
# test <- HMM.Train(index <- index,
#                   Data,
#                   start.date <- start.date,
#                   end.date   <- end.date,
#                   frequency=frequency,
#                   mult=mult,
#                   # mu0=mu.Test,
#                   # sigma0=sigma.Test,
#                   Gamma0=Gamma.HHMM,
#                   type="HHMM",
#                   distribution='Normal',
#                   Transition.Type="Homogeneous",
#                   PlotName = NULL,
#                   data.Origin=data.Origin,
#                   auto.assign=T,
#                   path=path,
#                   nbTicks=nbTicks)


# test <- HMM.Train(index <- index,
#                   Data,
#                   start.date <- start.date,
#                   end.date   <- end.date,
#                   frequency=frequency,
#                   mult=mult,
#                   # mu0=mu.Test,
#                   # sigma0=sigma.Test,
#                   Gamma0=Gamma.HHMM,
#                   type="HHMM",
#                   distribution='Student',
#                   Transition.Type="Homogeneous",
#                   PlotName = NULL,
#                   data.Origin=data.Origin,
#                   auto.assign=T,
#                   path=path,
#                   nbTicks=nbTicks)

